development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: sinatra-project-fiscord
  password: postgres
  database: sinatra-mvc-project-development
  pool: 2
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: production